# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'FirebaseUI-Sample1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseUI-Sample1
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
pod 'FirebaseUI/Auth'
end
